spring:
  data-source:
    url: jdbc:mysql://localhost:3307/bd_academika
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
server:
  port: 8081
jwt:
  secret: TuClaveSuperSecretaMuyLarga1234567890
  expiration: 36000000